traffic_project_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "123456"
      port: 5432
      dbname: traffic_dwh
      schema: public
      threads: 4            