CREATE TABLE IF NOT EXISTS "Fact_accident" (
	"fact_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"natural_id" INTEGER,
	"crash_id" INTEGER,
	"cause_id" INTEGER,
	"device_id" INTEGER,
	"datekey" INTEGER,
	"crash_hour" INTEGER,
	"damage" VARCHAR,
	"num_units" INTEGER,
	"most_severe_injury" VARCHAR,
	"injuries_total" INTEGER,
	"injuries_fatal" INTEGER,
	"injuries_incapacitating" INTEGER,
	"injuries_non_incapacitating" INTEGER,
	"injuries_reported_not_evident" INTEGER,
	"injuries_no_indication" INTEGER,
	"is_severe" BOOLEAN,
	"epdo_priority_score" INTEGER,
	PRIMARY KEY("fact_id")
);




CREATE TABLE IF NOT EXISTS "Dim_Crash_Type" (
	"crash_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"first_crash_type" VARCHAR,
	"alignment" VARCHAR,
	"crash_type" VARCHAR,
	"intersection_related_i" BOOLEAN,
	PRIMARY KEY("crash_id")
);




CREATE TABLE IF NOT EXISTS "Dim_Natural_Condition" (
	"natural_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"weather_condition" VARCHAR,
	"lighting_condition" VARCHAR,
	"roadway_surface_cond" VARCHAR,
	PRIMARY KEY("natural_id")
);




CREATE TABLE IF NOT EXISTS "Dim_Crash_Date" (
	"datekey" INTEGER NOT NULL UNIQUE,
	"year" INTEGER,
	"quarter" INTEGER,
	"month" INTEGER,
	"day" INTEGER,
	"hour" INTEGER,
	"dayofweek" VARCHAR,
	PRIMARY KEY("datekey")
);




CREATE TABLE IF NOT EXISTS "Dim_Cause" (
	"cause_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"primary_cause" VARCHAR,
	"cause_group" TEXT,
	PRIMARY KEY("cause_id")
);




CREATE TABLE IF NOT EXISTS "Dim_Traffic_Device" (
	"device_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"traffic_control_device" VARCHAR,
	"trafficway_type" VARCHAR,
	PRIMARY KEY("device_id")
);



ALTER TABLE "Dim_Crash_Date"
ADD FOREIGN KEY("datekey") REFERENCES "Fact_accident"("datekey")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Dim_Natural_Condition"
ADD FOREIGN KEY("natural_id") REFERENCES "Fact_accident"("natural_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Dim_Crash_Type"
ADD FOREIGN KEY("crash_id") REFERENCES "Fact_accident"("crash_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Dim_Cause"
ADD FOREIGN KEY("cause_id") REFERENCES "Fact_accident"("cause_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Dim_Traffic_Device"
ADD FOREIGN KEY("device_id") REFERENCES "Fact_accident"("device_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;